# Generated by Django 4.2.7 on 2025-08-29 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("ligue1", "Ligue 1 Professionnelle"),
                            ("ligue2", "Ligue 2 Professionnelle"),
                            ("c1", "Coupe de Tunisie"),
                            ("c2", "Coupe de la Ligue"),
                            ("youth", "Championnat Jeunes"),
                            ("regional", "Championnat Régional"),
                        ],
                        max_length=20,
                        verbose_name="Type de match",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("senior", "Seniors"),
                            ("u21", "U21"),
                            ("junior", "Juniors"),
                            ("cadets", "Cadets"),
                            ("minimes", "Minimes"),
                            ("school", "Scolaires"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("stadium", models.CharField(max_length=100, verbose_name="Stade")),
                ("match_date", models.DateField(verbose_name="Date du match")),
                ("match_time", models.TimeField(verbose_name="Heure du match")),
                (
                    "home_team",
                    models.CharField(max_length=50, verbose_name="Équipe domicile"),
                ),
                (
                    "away_team",
                    models.CharField(max_length=50, verbose_name="Équipe visiteur"),
                ),
                (
                    "home_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Score domicile"
                    ),
                ),
                (
                    "away_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Score visiteur"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description du match"
                    ),
                ),
                (
                    "match_sheet",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="match_sheets/",
                        verbose_name="Feuille de match",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programmé"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                            ("postponed", "Reporté"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "match_report",
                    models.TextField(
                        blank=True, null=True, verbose_name="Rapport de match"
                    ),
                ),
                (
                    "incidents",
                    models.TextField(blank=True, null=True, verbose_name="Incidents"),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Arbitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matchs",
                "ordering": ["-match_date", "-match_time"],
            },
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("yellow_card", "Carton jaune"),
                            ("red_card", "Carton rouge"),
                            ("goal", "But"),
                            ("penalty", "Pénalty"),
                            ("substitution", "Remplacement"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "team",
                    models.CharField(max_length=50, verbose_name="Équipe concernée"),
                ),
                (
                    "player_name",
                    models.CharField(max_length=100, verbose_name="Nom du joueur"),
                ),
                (
                    "minute",
                    models.PositiveIntegerField(verbose_name="Minute de l'événement"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="matches.match",
                        verbose_name="Match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de match",
                "verbose_name_plural": "Événements de match",
                "ordering": ["minute"],
            },
        ),
    ]
