# Generated by Django 4.2.7 on 2025-08-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_pushsubscription"),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_designation",
                    models.CharField(
                        choices=[
                            ("arbitre_principal", "Arbitre Principal"),
                            ("arbitre_assistant1", "1er Arbitre Assistant"),
                            ("arbitre_assistant2", "2ème Arbitre Assistant"),
                            ("quatrieme_arbitre", "4ème Arbitre"),
                            ("arbitre_video", "Arbitre VAR"),
                            ("arbitre_assistant_video", "Assistant VAR"),
                        ],
                        max_length=30,
                        verbose_name="Type de désignation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposée"),
                            ("accepted", "Acceptée"),
                            ("declined", "Refusée"),
                            ("confirmed", "Confirmée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="proposed",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_designation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de désignation"
                    ),
                ),
                (
                    "date_reponse",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de réponse"
                    ),
                ),
                (
                    "commentaires",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaires"
                    ),
                ),
                (
                    "raison_refus",
                    models.TextField(
                        blank=True, null=True, verbose_name="Raison du refus"
                    ),
                ),
                (
                    "notification_envoyee",
                    models.BooleanField(
                        default=False, verbose_name="Notification envoyée"
                    ),
                ),
                (
                    "date_notification",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date d'envoi de la notification",
                    ),
                ),
                (
                    "arbitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designations",
                        to="accounts.arbitre",
                        verbose_name="Arbitre",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designations",
                        to="matches.match",
                        verbose_name="Match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Désignation d'arbitrage",
                "verbose_name_plural": "Désignations d'arbitrage",
                "ordering": ["-date_designation"],
                "unique_together": {("match", "arbitre", "type_designation")},
            },
        ),
    ]
