# Generated by Django 4.2.7 on 2025-08-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_pushsubscription"),
        ("matches", "0002_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="referee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="accounts.arbitre",
                verbose_name="Arbitre",
            ),
        ),
    ]
