# Generated by Django 4.2.7 on 2025-09-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_alter_match_referee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=50, verbose_name="Nom de la catégorie"),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "age_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Âge minimum"
                    ),
                ),
                (
                    "age_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Âge maximum"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="TypeMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom du type de match"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Type de match",
                "verbose_name_plural": "Types de match",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.RemoveField(
            model_name="match",
            name="category",
        ),
        migrations.RemoveField(
            model_name="match",
            name="match_type",
        ),
        migrations.AddField(
            model_name="match",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="matches.categorie",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="type_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="matches.typematch",
                verbose_name="Type de match",
            ),
        ),
    ]
