# Generated by Django 4.2.7 on 2025-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_categorie_typematch_remove_match_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="role",
            field=models.CharField(
                choices=[
                    ("arbitre_principal", "Arbitre Principal"),
                    ("arbitre_assistant1", "1er Arbitre Assistant"),
                    ("arbitre_assistant2", "2ème Arbitre Assistant"),
                    ("quatrieme_arbitre", "4ème Arbitre"),
                    ("arbitre_video", "Arbitre VAR"),
                    ("arbitre_assistant_video", "Assistant VAR"),
                ],
                default="arbitre_principal",
                max_length=30,
                verbose_name="Rôle de l'arbitre",
            ),
        ),
    ]
