# Generated by Django 4.2.7 on 2025-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcuseArbitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_arbitre', models.CharField(max_length=100, verbose_name="Nom de l'arbitre")),
                ('prenom_arbitre', models.CharField(max_length=100, verbose_name="Prénom de l'arbitre")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('cause', models.TextField(verbose_name="Cause de l'excuse")),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='excuses/', verbose_name='Pièce jointe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Excuse d'arbitre",
                'verbose_name_plural': "Excuses d'arbitres",
                'ordering': ['-created_at'],
            },
        ),
    ]
