# Generated by Django 4.2.7 on 2025-09-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_excusearbitre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarificationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(choices=[('championnat', 'Championnat'), ('coupe_tunisie_seniors', 'Coupe de Tunisie Seniors'), ('coupe_tunisie_jeunes', 'Coupe de Tunisie Jeunes'), ('super_coupe', 'Super Coupe de Tunisie'), ('matchs_amicaux', 'Matchs Amicaux')], max_length=50, verbose_name='Compétition')),
                ('division', models.CharField(blank=True, choices=[('seniors', 'Seniors'), ('jeunes', 'Jeunes'), ('feminin', 'Féminin'), ('cadettes', 'Cadettes')], max_length=20, null=True, verbose_name='Division')),
                ('type_match', models.CharField(choices=[('ligue1', 'Ligue 1'), ('ligue2', 'Ligue 2'), ('c1', 'C1'), ('c2', 'C2'), ('ff', 'FF'), ('reg', 'Régional'), ('1_8', '1/8 de finale'), ('1_4', '1/4 de finale'), ('1_2', '1/2 de finale'), ('finale', 'Finale'), ('u21_u19', 'U21/U19'), ('u17_u16_u15_u14', 'U17/U16/U15/U14'), ('feminin_cadettes', 'Féminin Cadettes'), ('super_coupe_seniors', 'Super Coupe Seniors'), ('seniors_amical', 'Seniors Amical'), ('u21_u19_amical', 'U21/U19 Amical'), ('u15_u14_amical', 'U15/U14 Amical'), ('eq_nat_vs_club_seniors', 'Équipe Nationale vs Club Seniors'), ('eq_nat_vs_club_u21_u19', 'Équipe Nationale vs Club U21/U19'), ('eq_nat_vs_club_u15_u14', 'Équipe Nationale vs Club U15/U14')], max_length=50, verbose_name='Type de match')),
                ('role', models.CharField(choices=[('arbitre', 'Arbitre'), ('assistant', 'Assistant'), ('4eme_arbitre', '4ème Arbitre'), ('commissaire', 'Commissaire')], max_length=20, verbose_name='Rôle')),
                ('tarif', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Tarif (TND)')),
                ('devise', models.CharField(default='TND', max_length=3, verbose_name='Devise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Tarification de match',
                'verbose_name_plural': 'Tarifications de matchs',
                'ordering': ['competition', 'division', 'type_match', 'role'],
                'unique_together': {('competition', 'division', 'type_match', 'role')},
            },
        ),
    ]
