# Generated by Django 4.2.7 on 2025-08-29 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Titre en français"),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="Titre en arabe"),
                ),
                ("content_fr", models.TextField(verbose_name="Contenu en français")),
                ("content_ar", models.TextField(verbose_name="Contenu en arabe")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="news/videos/",
                        verbose_name="Vidéo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="À la une"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualité",
                "verbose_name_plural": "Actualités",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
