# Generated by Django 4.2.7 on 2025-08-30 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="author",
        ),
        migrations.AddField(
            model_name="news",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Type d'auteur",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID de l'auteur"
            ),
        ),
    ]
