# Generated by Django 4.2.7 on 2025-08-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LigueArbitrage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code de la ligue"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la ligue"
                    ),
                ),
                ("region", models.CharField(max_length=50, verbose_name="Région")),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Ligue active"),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligue d'Arbitrage",
                "verbose_name_plural": "Ligues d'Arbitrage",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.RemoveField(
            model_name="arbitre",
            name="league",
        ),
        migrations.AddField(
            model_name="arbitre",
            name="niveau_competition",
            field=models.CharField(
                choices=[
                    ("ligue1", "Ligue 1 Professionnelle"),
                    ("ligue2", "Ligue 2 Professionnelle"),
                    ("amateur", "Ligue Nationale Amateur"),
                    ("regional", "Ligue Régionale"),
                ],
                default="amateur",
                max_length=20,
                verbose_name="Niveau de compétition",
            ),
        ),
        migrations.AddField(
            model_name="arbitre",
            name="ligue_arbitrage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.liguearbitrage",
                verbose_name="Ligue d'Arbitrage",
            ),
        ),
    ]
