# Generated by Django 4.2.7 on 2025-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_arbitre_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitre",
            name="birth_place",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Lieu de naissance"
            ),
        ),
    ]
