# Generated by Django 4.2.7 on 2025-08-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0004_arbitre_birth_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arbitre",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Arbitre/Commissaire",
                "verbose_name_plural": "Arbitres/Commissaires",
            },
        ),
        migrations.AddField(
            model_name="arbitre",
            name="user_type",
            field=models.CharField(
                choices=[("arbitre", "Arbitre"), ("commissaire", "Commissaire")],
                default="arbitre",
                max_length=20,
                verbose_name="Type d'utilisateur mobile",
            ),
        ),
        migrations.AlterField(
            model_name="arbitre",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="arbitre_user_set",
                related_query_name="arbitre_user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="arbitre",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="arbitre_user_set",
                related_query_name="arbitre_user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "username",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nom d'utilisateur"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("super_admin", "Super Administrateur"),
                        ],
                        default="admin",
                        max_length=20,
                        verbose_name="Type d'utilisateur",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=True, verbose_name="Membre du staff"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, verbose_name="Super administrateur"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière connexion"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="admin_user_set",
                        related_query_name="admin_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="admin_user_set",
                        related_query_name="admin_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrateur",
                "verbose_name_plural": "Administrateurs",
                "ordering": ["-date_joined"],
            },
        ),
    ]
