# Generated by Django 4.2.7 on 2025-08-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0005_alter_arbitre_options_arbitre_user_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arbitre",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Arbitre",
                "verbose_name_plural": "Arbitres",
            },
        ),
        migrations.RemoveField(
            model_name="arbitre",
            name="user_type",
        ),
        migrations.AlterField(
            model_name="arbitre",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="arbitre",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
