# Generated by Django 4.2.7 on 2025-08-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_liguearbitrage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liguearbitrage",
            options={
                "ordering": ["ordre", "nom"],
                "verbose_name": "Ligue d'arbitrage",
                "verbose_name_plural": "Ligues d'arbitrage",
            },
        ),
        migrations.AddField(
            model_name="liguearbitrage",
            name="code",
            field=models.CharField(
                default=0, max_length=20, unique=True, verbose_name="Code de la ligue"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="liguearbitrage",
            name="ordre",
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
