# Generated by Django 4.2.7 on 2025-08-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_liguearbitrage_options_liguearbitrage_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liguearbitrage",
            name="code",
        ),
        migrations.RemoveField(
            model_name="liguearbitrage",
            name="region",
        ),
    ]
