# Generated by Django 4.2.7 on 2025-08-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_liguearbitrage_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(verbose_name="Endpoint de notification")),
                ("p256dh", models.TextField(verbose_name="Clé publique P-256 DH")),
                ("auth", models.TextField(verbose_name="Clé d'authentification")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Abonnement actif"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "arbitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="accounts.arbitre",
                        verbose_name="Arbitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement Push",
                "verbose_name_plural": "Abonnements Push",
                "ordering": ["-created_at"],
                "unique_together": {("arbitre", "endpoint")},
            },
        ),
    ]
