# Generated by Django 4.2.7 on 2025-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitre",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
