# Generated by Django 4.2.7 on 2025-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_arbitre_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitre",
            name="grade",
            field=models.CharField(
                choices=[
                    ("candidat", "Candidat"),
                    ("3eme_serie", "3ème Série"),
                    ("2eme_serie", "2ème Série"),
                    ("1ere_serie", "1ère Série"),
                    ("federale", "Fédérale"),
                ],
                default="candidat",
                max_length=20,
                verbose_name="Grade d'arbitrage",
            ),
        ),
    ]
