# Generated by Django 4.2.7 on 2025-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_arbitre_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitre",
            name="role",
            field=models.CharField(
                choices=[("arbitre", "Arbitre"), ("assistant", "Assistant")],
                default="arbitre",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
