# Generated by Django 4.2.7 on 2025-09-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_arbitre_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Token FCM"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                        verbose_name="Type d'appareil",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID de l'appareil",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Version de l'app",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Token actif"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to="accounts.admin",
                        verbose_name="Administrateur",
                    ),
                ),
                (
                    "arbitre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to="accounts.arbitre",
                        verbose_name="Arbitre",
                    ),
                ),
                (
                    "commissaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to="accounts.commissaire",
                        verbose_name="Commissaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token FCM",
                "verbose_name_plural": "Tokens FCM",
                "db_table": "fcm_tokens",
                "ordering": ["-created_at"],
                "unique_together": {("token",)},
            },
        ),
    ]
