# Generated by Django 4.2.7 on 2025-09-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_fcmtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDesignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.IntegerField(verbose_name="ID du match")),
                (
                    "match_nom",
                    models.CharField(max_length=200, verbose_name="Nom du match"),
                ),
                ("match_date", models.DateTimeField(verbose_name="Date du match")),
                (
                    "match_lieu",
                    models.CharField(max_length=200, verbose_name="Lieu du match"),
                ),
                (
                    "designation_type",
                    models.CharField(
                        choices=[
                            ("arbitre_principal", "Arbitre Principal"),
                            ("arbitre_assistant_1", "Assistant 1"),
                            ("arbitre_assistant_2", "Assistant 2"),
                            ("arbitre_quatrieme", "Quatrième Arbitre"),
                            ("commissaire_match", "Commissaire de Match"),
                        ],
                        max_length=30,
                        verbose_name="Type de désignation",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Envoyée"),
                            ("delivered", "Livrée"),
                            ("read", "Lue"),
                            ("failed", "Échouée"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Notification lue"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "fcm_response",
                    models.JSONField(blank=True, null=True, verbose_name="Réponse FCM"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "arbitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designation_notifications",
                        to="accounts.arbitre",
                        verbose_name="Arbitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification de Désignation",
                "verbose_name_plural": "Notifications de Désignation",
                "db_table": "notification_designations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["arbitre", "-created_at"],
                        name="notificatio_arbitre_295f43_idx",
                    ),
                    models.Index(
                        fields=["match_id"], name="notificatio_match_i_efdae0_idx"
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_429702_idx"
                    ),
                ],
            },
        ),
    ]
