# Generated by Django 4.2.7 on 2025-09-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_notificationdesignation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcuseArbitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        help_text="Date de début de l'indisponibilité",
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        help_text="Date de fin de l'indisponibilité",
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "cause",
                    models.TextField(
                        help_text="Description détaillée de la raison de l'excuse",
                        verbose_name="Cause de l'excuse",
                    ),
                ),
                (
                    "piece_jointe",
                    models.ImageField(
                        blank=True,
                        help_text="Document justificatif (optionnel)",
                        null=True,
                        upload_to="excuses/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En Attente"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "commentaire_admin",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Commentaire de l'administration",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "traite_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "arbitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excuses",
                        to="accounts.arbitre",
                        verbose_name="Arbitre",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excuses_traitees",
                        to="accounts.admin",
                        verbose_name="Traité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Excuse d'Arbitre",
                "verbose_name_plural": "Excuses d'Arbitres",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["arbitre", "status"],
                        name="accounts_ex_arbitre_710760_idx",
                    ),
                    models.Index(
                        fields=["date_debut", "date_fin"],
                        name="accounts_ex_date_de_9facb3_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="accounts_ex_status_59d685_idx",
                    ),
                ],
            },
        ),
    ]
