# Generated by Django 4.2.7 on 2025-09-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_excusearbitre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token de réinitialisation')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('is_used', models.BooleanField(default=False, verbose_name='Token utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='accounts.admin', verbose_name='Administrateur')),
                ('arbitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='accounts.arbitre', verbose_name='Arbitre')),
                ('commissaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='accounts.commissaire', verbose_name='Commissaire')),
            ],
            options={
                'verbose_name': 'Token de Réinitialisation',
                'verbose_name_plural': 'Tokens de Réinitialisation',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='password_re_token_060a1f_idx'), models.Index(fields=['email'], name='password_re_email_2bb9da_idx'), models.Index(fields=['expires_at'], name='password_re_expires_8e96b7_idx'), models.Index(fields=['is_used'], name='password_re_is_used_eabc82_idx')],
            },
        ),
    ]
