# Generated by Django 4.2.7 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_code',
            field=models.CharField(default=' ', max_length=6, verbose_name='Code OTP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_verified',
            field=models.BooleanField(default=False, verbose_name='OTP vérifié'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification OTP'),
        ),
    ]
