# Generated by Django 4.2.7 on 2025-09-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_passwordresettoken_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeArbitrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du grade')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau', models.IntegerField(default=1, verbose_name='Niveau du grade')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Grade actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Grade d'arbitrage",
                'verbose_name_plural': "Grades d'arbitrage",
                'ordering': ['ordre', 'niveau', 'nom'],
            },
        ),
    ]
